# Generated by Django 3.1.7 on 2021-02-27 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tinder_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('Man', 'Мужчина'), ('Woman', 'Женжина')], default=0, max_length=6, verbose_name='Пол'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProfilePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photoprofiles/', verbose_name='Фото')),
                ('date_pub', models.DateTimeField(auto_now=True, verbose_name='Дата публикации')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profilephoto', to='tinder_app.profile')),
            ],
        ),
    ]
