# Generated by Django 3.1.7 on 2021-02-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder_app', '0002_auto_20210227_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilephoto',
            options={'ordering': ['profile'], 'verbose_name': 'Фото профиля', 'verbose_name_plural': 'Фото профилей'},
        ),
        migrations.AddField(
            model_name='profile',
            name='main_photo',
            field=models.ImageField(blank=True, null=True, upload_to='mainphoto/', verbose_name='Главное фото'),
        ),
    ]
