# Generated by Django 3.1.7 on 2021-03-01 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tinder_app', '0005_auto_20210228_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='user_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_like', to='tinder_app.profile', verbose_name='От кого'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_like', to='tinder_app.profile', verbose_name='Кому'),
        ),
    ]
