# Generated by Django 3.1.7 on 2021-03-01 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tinder_app', '0006_auto_20210301_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileForToday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tinder_app.profile')),
            ],
            options={
                'verbose_name': 'Профиль на сегодня',
                'verbose_name_plural': 'Профили на сегодня',
            },
        ),
    ]
