# Generated by Django 3.1.7 on 2021-03-02 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tinder_app', '0009_unlike'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Начало общения')),
                ('member_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_chat_1', to='tinder_app.profile', verbose_name='Участник_1')),
                ('member_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_chat_2', to='tinder_app.profile', verbose_name='Участник_2')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чат',
            },
        ),
    ]
