# Generated by Django 3.1.7 on 2021-03-04 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tinder_app', '0013_message_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='tinder_app.chat', verbose_name='Чат'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user_from', 'user_to')},
        ),
    ]
