# Generated by Django 3.1.7 on 2021-03-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder_app', '0014_auto_20210304_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Локация'),
        ),
    ]
