# Generated by Django 3.1.7 on 2021-03-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder_app', '0015_auto_20210305_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sub_type',
            field=models.CharField(choices=[('1', 'Базовая'), ('2', 'Вип'), ('3', 'Премиум')], default=1, max_length=1, verbose_name='Тип подписки'),
        ),
    ]
