# Generated by Django 3.1.7 on 2021-03-07 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinder_app', '0016_profile_sub_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('member_1', 'member_2')},
        ),
        migrations.AlterUniqueTogether(
            name='reciprocity',
            unique_together={('user_1', 'user_2')},
        ),
        migrations.AlterUniqueTogether(
            name='unlike',
            unique_together={('user_from', 'user_to')},
        ),
    ]
